version: '3.4'

services:

  node:
    build:
      args:
        - NODE_ENV=test
        - DATABASE_HOST=db
        - DATABASE_USER=postgres
    command: npm run test
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=test
      - DATABASE_HOST=db
      - DATABASE_USER=postgres
    healthcheck:
      disable: true
